name: Verify test status
on: [push]

jobs:
  verify:
    name: Verify test status
    runs-on: ubuntu-20.04
    steps:
      - name: Get status
        uses: https://git.samerion.com/Actions/GithubStatus@main
        with:
            token: ${{ secrets.GH_TOKEN }}
            event: push
