name: Run all tests
on: [push]

jobs:
  test:
    name: DUB tests
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest, macos-13]
        dc: [dmd, ldc, ldc-1.28.1]
        #dub: [dub, redub]
        #os: [ubuntu-latest, windows-latest]  # DEBUG
        dub: [dub]                           # DEBUG
        exclude:
          - { os: macos-latest, dc: dmd }
          - { os: macos-13, dc: dmd }

    runs-on: ${{ matrix.os }}
    env: 
      DUB: dub
    steps:
      - uses: actions/checkout@v4
      - name: Install D compiler
        uses: dlang-community/setup-dlang@v2
        with:
          compiler: ${{ matrix.dc }}

      - name: Install Redub
        if: matrix.dub == 'redub'
        shell: bash
        run: |
          dub fetch redub
          echo "DUB=dub run redub" >> "$GITHUB_ENV"

      # - name: Test moduleView
      #   shell: bash
      #   run: $DUB test :module-view -d Fluid_BuildMessages
      #   if: matrix.dc != 'ldc-1.28.1'

      - name: Compile tour
        shell: bash
        run: $DUB build :tour
        if: matrix.dc != 'ldc-1.28.1'

      - name: Run tests
        shell: bash
        run: $DUB test
